// <auto-generated />
using System;
using FazendaWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FazendaWeb.Migrations
{
    [DbContext(typeof(FazendaWebContext))]
    [Migration("20190410211932_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FazendaWeb.Models.Rebanho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Nome");

                    b.Property<string>("Origem");

                    b.Property<string>("Raca");

                    b.Property<string>("Sexo");

                    b.HasKey("Id");

                    b.ToTable("Rebanho");
                });
#pragma warning restore 612, 618
        }
    }
}
