// <auto-generated />
using System;
using FazendaWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FazendaWeb.Migrations
{
    [DbContext(typeof(FazendaWebContext))]
    partial class FazendaWebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FazendaWeb.Models.Pasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Area");

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("Pasto");
                });

            modelBuilder.Entity("FazendaWeb.Models.Rebanho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Nome");

                    b.Property<string>("Origem");

                    b.Property<int?>("PastoId");

                    b.Property<string>("Raca");

                    b.Property<string>("Sexo");

                    b.HasKey("Id");

                    b.HasIndex("PastoId");

                    b.ToTable("Rebanho");
                });

            modelBuilder.Entity("FazendaWeb.Models.Rebanho", b =>
                {
                    b.HasOne("FazendaWeb.Models.Pasto", "Pasto")
                        .WithMany("Rebanhos")
                        .HasForeignKey("PastoId");
                });
#pragma warning restore 612, 618
        }
    }
}
